class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/zyh/DAVLT/'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/home/zyh/DAVLT/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/data3/hly/DAVLT/pretrained_networks'
        self.lang_anno_dir = '/home/zyh/datasets/MGIT/anno/'
        self.mgit_dir = '/home/zyh/datasets/MGIT'
        self.lasot_dir = '/home/zyh/datasets/lasot/'
        self.tnl2k_dir = '/home/zyh/datasets/tnl2k/TNL2K_train_subset'
        self.got10k_dir = '/home/zyh/datasets/got10k/train'
        self.got10k_val_dir = '/home/datasets/GOT_10k/val'
        self.lasot_lmdb_dir = '/home/zyh/DAVLT/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/home/zyh/DAVLT/data/got10k_lmdb'
        self.trackingnet_dir = '/home/zyh/datasets/TrackingNet'
        self.trackingnet_lmdb_dir = '/home/zyh/DAVLT/data/trackingnet_lmdb'
        self.coco_dir = '/home/zyh/DAVLT/data/coco'
        self.coco_lmdb_dir = '/home/zyh/DAVLT/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/home/zyh/DAVLT/data/vid'
        self.imagenet_lmdb_dir = '/home/zyh/DAVLT/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
